package fxrubkinkuutio.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import fxrubkinkuutio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.29 17:37:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {


  // Generated by ComTest BEGIN  // Rekisteri: 15
   private Rekisteri rekisteri; 
   private Ratkaisu rat1; 
   private Ratkaisu rat2; 
   private int rid1; 
   private int rid2; 
   private Sekoitus sek1; 
   private Sekoitus sek2; 

   public void alustaRekisteri() {
     rekisteri = new Rekisteri(); 
     rat1 = new Ratkaisu(); rat1.testiArvot(); rat1.rekisteroi(); 
     rat2 = new Ratkaisu(); rat2.testiArvot(); rat2.rekisteroi(); 
     rid1 = rat1.getId(); 
     rid2 = rat2.getId(); 
     sek1 = new Sekoitus(rid1); sek1.testiArvot(rid1); sek1.rekisteroi(); 
     sek2 = new Sekoitus(rid2); sek2.testiArvot(rid2); sek2.rekisteroi(); 
     try {
     rekisteri.lisaa(rat1); 
     rekisteri.lisaa(rat2); 
     rekisteri.lisaa(sek1); 
     rekisteri.lisaa(sek2); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista60 
   * @throws Exception when error
   */
  @Test
  public void testPoista60() throws Exception {    // Rekisteri: 60
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 63", 2, rekisteri.getRatkaisuja()); 
    assertEquals("From: Rekisteri line: 64", 1, rekisteri.poista(rat1)); 
    assertEquals("From: Rekisteri line: 65", 1, rekisteri.getRatkaisuja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa80 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa80() throws SailoException {    // Rekisteri: 80
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 83", 2, rekisteri.getRatkaisuja()); 
    rekisteri.lisaa(rat1); 
    assertEquals("From: Rekisteri line: 85", 3, rekisteri.getRatkaisuja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa116 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa116() throws SailoException {    // Rekisteri: 116
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 119", 2, rekisteri.getRatkaisuja()); 
    rekisteri.korvaaTaiLisaa(rat1); 
    assertEquals("From: Rekisteri line: 121", 2, rekisteri.getRatkaisuja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi160 
   * @throws CloneNotSupportedException when error
   * @throws SailoException when error
   */
  @Test
  public void testEtsi160() throws CloneNotSupportedException, SailoException {    // Rekisteri: 160
    alustaRekisteri(); 
    Ratkaisu ratkaisu3 = new Ratkaisu(); ratkaisu3.rekisteroi(); 
    ratkaisu3.setAika("00;34,242"); 
    rekisteri.lisaa(ratkaisu3); 
    Collection<Ratkaisu> loytyneet = rekisteri.etsi("*34*"); 
    assertEquals("From: Rekisteri line: 167", 1, loytyneet.size()); 
    Iterator<Ratkaisu> it = loytyneet.iterator(); 
    assertEquals("From: Rekisteri line: 169", true, it.next() == ratkaisu3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaSekoitukset221 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaSekoitukset221() throws SailoException {    // Rekisteri: 221
    alustaRekisteri(); 
    List<Sekoitus> loytyneet; 
    loytyneet = rekisteri.annaSekoitukset(rat1); 
    assertEquals("From: Rekisteri line: 228", 1, loytyneet.size()); 
    assertEquals("From: Rekisteri line: 229", true, loytyneet.get(0) == sek1); 
  } // Generated by ComTest END
}